### Create a new user
POST {{baseUrl}}/user/create
Content-Type: application/json

{
  "email": "jerry@test.me",
  "firstName": "Jerry",
  "lastName": "Mustermann",
  "password": "Sicheres Passwort",
  "profilePicture": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
  "roles": []
}

### Login to a user account
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

> {%
    client.global.set("accessToken", response.body.accessToken)
    client.global.set("refreshToken", response.body.refreshToken)
%}

### Get current user
GET {{baseUrl}}/user/current
Authorization: Bearer {{accessToken}}